# Generated by Django 4.1.4 on 2023-06-28 06:26

from django.db import migrations, models
import django.db.models.deletion
import eapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eapp', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, upload_to=eapp.models.getFileName)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('Product_image', models.ImageField(blank=True, upload_to=eapp.models.getFileName)),
                ('quantity', models.IntegerField(blank=True)),
                ('price', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.category')),
            ],
        ),
    ]
